# Jenkins-project
Brief about Jenkins and how to (build end to end pipelines)?
Firstly, we will launch EC2 instance,then install jenkins and use docker as agent, setup CI/CD and deploy applications 

# AWS EC2 instance
* Go to AWS console
* Launch EC2 instances
